# Generated by Django 4.0.6 on 2022-07-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardSeries', models.IntegerField()),
                ('cardNumber', models.IntegerField()),
                ('issueDate', models.DateField()),
                ('cardExpirationDate', models.DateField()),
                ('CVVCode', models.IntegerField()),
                ('cardAmount', models.IntegerField()),
                ('status', models.CharField(choices=[('in', 'Inactivated'), ('ac', 'Activated'), ('ov', 'Overdue')], max_length=2)),
            ],
        ),
    ]
