# Generated by Django 4.0.6 on 2022-07-13 11:28

import creditCards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditCards', '0002_remove_creditcard_id_creditcard_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='history',
            field=models.JSONField(default=creditCards.models.CreditCard.historyDefault, verbose_name='Історія транзакцій'),
        ),
    ]
