# Generated by Django 4.0.6 on 2022-07-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditCards', '0003_alter_creditcard_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='cardAmount',
            field=models.IntegerField(default=0, verbose_name='Сума на рахунку'),
        ),
    ]
