# Generated by Django 4.0.6 on 2022-07-13 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditCards', '0004_alter_creditcard_cardamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='cardNumber',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Номер картки'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='cardSeries',
            field=models.IntegerField(verbose_name='Серія картки'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='issueDate',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата видачі'),
        ),
    ]
