# Generated by Django 4.0.6 on 2022-07-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditCards', '0005_alter_creditcard_cardnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='cardExpirationDate',
            field=models.DateTimeField(blank=True, verbose_name='Строк придатності'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='cardNumber',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Номер картки'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='issueDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата видачі'),
        ),
    ]
