# Generated by Django 4.0.6 on 2022-07-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditCards', '0006_alter_creditcard_cardexpirationdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='cardExpirationDate',
            field=models.DateTimeField(verbose_name='Строк придатності'),
        ),
    ]
