# Generated by Django 4.0.6 on 2022-07-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditCards', '0007_alter_creditcard_cardexpirationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='CVVCode',
            field=models.CharField(max_length=3, verbose_name='Захисний код'),
        ),
    ]
